; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.32"

; Modules
projects[ctools][version] = "1.4"

projects[ckeditor][version] = "1.16"

projects[media][version] = "1.4"

projects[flag][version] = "3.5"

projects[flag_friend][version] = "2.0-alpha1"

projects[galleryformatter][version] = "1.3"

projects[google_analytics][version] = "1.4"

projects[jplayer][version] = "2.0-beta1"

projects[mass_pwreset][version] = "1.0"

projects[pathauto][version] = "1.2"

projects[token][version] = "1.5"

projects[views][version] = "3.8"

; Themes
projects[adaptivetheme][version] = "3.1"


