version: '2'
services:
  # data:
  #   image: tianon/true
  #   volumes:
  #     - ./docroot:/var/www/html
  deninet.dev:
    build: .docker/web
    ports:
      - "80:80"
    volumes_from:
      - php
    depends_on:
      - php
  php:
    build: .docker/php
    volumes:
      - ./docroot:/var/www/html
    env_file:
      - .env
  db:
    image: wodby/drupal-mariadb
    env_file:
      - .env
    volumes:
      - /var/lib/mysql
      - ./db-backups:/tmp/db-backups
  # cli:
  #   build: .docker/cli
  #   volumes_from:
  #     - php
  #   env_file:
  #     - .env
  # varnish:
  #   image: wodby/drupal-varnish
  #   # restart: always
  #   depends_on:
  #     - deninet.dev
  #   env_file:
  #     - .env
  #   ports:
  #     - "8004:6081" # HTTP Proxy
  #     - "8005:6082" # Control terminal
  # memcache:
  #   image: memcached:alpine
    # restart: always
  # browser:
  #   hostname: browser
  #   image: selenium/standalone-firefox
  #   ports:
  #     - "4444:4444"
