version: '2'
services:
  deninet.dev:
     build: .docker/web
     ports:
        - "80:80"
     volumes:
        - ./docroot:/var/www/html
  db:
     image: mariadb
     ports:
        - 3306:3306
     environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=deninet_com
        - MYSQL_USER=deninet
        - MYSQL_PASSWORD=thisisawesome
     volumes:
        - /var/lib/mysql
  cli:
     build: .docker/cli
     volumes:
        - ./tests:/var/tests
     volumes_from:
        - deninet.dev
     environment:
        - DRUPAL_USER=admin
        - DRUPAL_PASSWORD=password
        - MYSQL_DATABASE=deninet_com
        - MYSQL_USER=deninet
        - MYSQL_PASSWORD=thisisawesome
  memcache:
    image: memcached
    ports:
      - "11211:11211"
  browser:
    hostname: browser
    image: selenium/standalone-firefox
    ports:
      - "4444:4444"
