version: '2'
services:
  # data:
  #   image: tianon/true
  #   volumes:
  #     - ./docroot:/var/www/html
  deninet.dev:
    build: .docker/web
    ports:
      - "80:80"
    volumes_from:
      - php
    depends_on:
      - php
  php:
    build: .docker/php
    volumes:
      - ./docroot:/var/www/html
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - VARNISH_SECRET=${VARNISH_SECRET}
  db:
    image: mariadb
    # build: .docker/db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /var/lib/mysql
      - ./db-backups:/tmp/db-backups
  cli:
    build: .docker/cli
    volumes_from:
      - php
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  varnish:
    image: wodby/drupal-varnish
    # restart: always
    depends_on:
      - deninet.dev
    environment:
      - VARNISH_SECRET=${VARNISH_SECRET}
      - VARNISH_BACKEND_HOST=deninet.dev
      - VARNISH_BACKEND_PORT=80
      - VARNISH_MEMORY_SIZE=256M
      - VARNISH_STORAGE_SIZE=1024M
    ports:
      - "8004:6081" # HTTP Proxy
      - "8005:6082" # Control terminal
  memcache:
    image: memcached:alpine
    # restart: always
  # browser:
  #   hostname: browser
  #   image: selenium/standalone-firefox
  #   ports:
  #     - "4444:4444"
