; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.33"

; Profiles
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[deninet][download][type] = ""
projects[deninet][download][url] = ""
projects[deninet][type] = "profile"

; Modules
projects[ctools][version] = "1.4"

projects[ckeditor][version] = "1.16"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[deninet_blog][download][type] = ""
projects[deninet_blog][download][url] = ""
projects[deninet_blog][type] = "module"
projects[deninet_blog][version] = "1.0-beta1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[deninet_comments][download][type] = ""
projects[deninet_comments][download][url] = ""
projects[deninet_comments][type] = "module"
projects[deninet_comments][version] = "1.0-beta1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[deninet_content][download][type] = ""
projects[deninet_content][download][url] = ""
projects[deninet_content][type] = "module"
projects[deninet_content][version] = "1.0-beta1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[deninet_friends][download][type] = ""
projects[deninet_friends][download][url] = ""
projects[deninet_friends][type] = "module"
projects[deninet_friends][version] = "1.0-beta1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[deninet_google_analytics][download][type] = ""
projects[deninet_google_analytics][download][url] = ""
projects[deninet_google_analytics][type] = "module"
projects[deninet_google_analytics][version] = "1.0-beta1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[deninet_media][download][type] = ""
projects[deninet_media][download][url] = ""
projects[deninet_media][type] = "module"
projects[deninet_media][version] = "1.0-beta1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[deninet_path][download][type] = ""
projects[deninet_path][download][url] = ""
projects[deninet_path][type] = "module"
projects[deninet_path][version] = "1.0-beta1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[deninet_picture][download][type] = ""
projects[deninet_picture][download][url] = ""
projects[deninet_picture][type] = "module"
projects[deninet_picture][version] = "1.0-beta1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[deninet_podcasts][download][type] = ""
projects[deninet_podcasts][download][url] = ""
projects[deninet_podcasts][type] = "module"
projects[deninet_podcasts][version] = "1.0-beta1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[deninet_search][download][type] = ""
projects[deninet_search][download][url] = ""
projects[deninet_search][type] = "module"
projects[deninet_search][version] = "1.0-beta1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[deninet_sitewide_config][download][type] = ""
projects[deninet_sitewide_config][download][url] = ""
projects[deninet_sitewide_config][type] = "module"
projects[deninet_sitewide_config][version] = "1.0-beta1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[deninet_user][download][type] = ""
projects[deninet_user][download][url] = ""
projects[deninet_user][type] = "module"
projects[deninet_user][version] = "1.0-beta1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[deninet_views][download][type] = ""
projects[deninet_views][download][url] = ""
projects[deninet_views][type] = "module"
projects[deninet_views][version] = "1.0-beta1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[deninet_wiki][download][type] = ""
projects[deninet_wiki][download][url] = ""
projects[deninet_wiki][type] = "module"
projects[deninet_wiki][version] = "1.0-beta1"

projects[features][version] = "2.2"

projects[media][version] = "1.4"

projects[flag][version] = "3.5"

projects[flag_friend][version] = "2.0-alpha1"

projects[galleryformatter][version] = "1.3"

projects[google_analytics][version] = "1.4"

projects[jplayer][version] = "2.0-beta1"

projects[libraries][version] = "2.2"

projects[navbar][version] = "1.4"

projects[pathauto][version] = "1.2"

projects[token][version] = "1.5"

projects[views][version] = "3.8"

; Themes
projects[adaptivetheme][version] = "3.2"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[var][download][type] = ""
projects[var][download][url] = ""
projects[var][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[backbone][download][type] = "file"
libraries[backbone][download][url] = "http://backbonejs.org/backbone-min.js"
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = "file"
libraries[ckeditor][download][url] = "http://cdn.ckeditor.com/4.4.5/standard/ckeditor.js"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jplayer][download][type] = "get"
libraries[jplayer][download][url] = "http://www.jplayer.org/latest/jQuery.jPlayer.2.7.0.zip"
libraries[jplayer][directory_name] = "jplayer"
libraries[jplayer][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[modernizr][download][type] = "get"
libraries[modernizr][download][url] = "https://github.com/Modernizr/Modernizr/archive/master.zip"
libraries[modernizr][directory_name] = "modernizr"
libraries[modernizr][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[underscore][download][type] = "file"
libraries[underscore][download][url] = "http://underscorejs.org/underscore-min.js"
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type] = "library"


