; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.32"

; Modules
projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.4"

projects[ckeditor][subdir] = "contrib"
projects[ckeditor][version] = "1.16"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[deninet_friends][download][type] = ""
projects[deninet_friends][download][url] = ""
projects[deninet_friends][type] = "module"
projects[deninet_friends][subdir] = "features"
projects[deninet_friends][version] = "1.0-beta1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[deninet_podcasts][download][type] = ""
projects[deninet_podcasts][download][url] = ""
projects[deninet_podcasts][type] = "module"
projects[deninet_podcasts][subdir] = "features"
projects[deninet_podcasts][version] = "1.0-beta1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[deninet_sitewide_config][download][type] = ""
projects[deninet_sitewide_config][download][url] = ""
projects[deninet_sitewide_config][type] = "module"
projects[deninet_sitewide_config][subdir] = "features"
projects[deninet_sitewide_config][version] = "1.0-beta1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[deninet_wiki][download][type] = ""
projects[deninet_wiki][download][url] = ""
projects[deninet_wiki][type] = "module"
projects[deninet_wiki][subdir] = "features"
projects[deninet_wiki][version] = "1.0-beta1"

projects[features][subdir] = "contrib"
projects[features][version] = "2.2"

projects[media][subdir] = "contrib"
projects[media][version] = "1.4"

projects[flag][subdir] = "contrib"
projects[flag][version] = "3.5"

projects[flag_friend][subdir] = "contrib"
projects[flag_friend][version] = "2.0-alpha1"

projects[galleryformatter][subdir] = "contrib"
projects[galleryformatter][version] = "1.3"

projects[google_analytics][subdir] = "contrib"
projects[google_analytics][version] = "1.4"

projects[jplayer][subdir] = "contrib"
projects[jplayer][version] = "2.0-beta1"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"

projects[mass_pwreset][subdir] = "contrib"
projects[mass_pwreset][version] = "1.0"

projects[navbar][subdir] = "contrib"
projects[navbar][version] = "1.4"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[views][subdir] = "contrib"
projects[views][version] = "3.8"

; Themes
projects[adaptivetheme][version] = "3.2"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[backbone][download][type] = "file"
libraries[backbone][download][url] = "http://backbonejs.org/backbone-min.js"
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = "file"
libraries[ckeditor][download][url] = "http://cdn.ckeditor.com/4.4.5/standard/ckeditor.js"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jplayer][download][type] = "get"
libraries[jplayer][download][url] = "http://www.jplayer.org/latest/jQuery.jPlayer.2.7.0.zip"
libraries[jplayer][directory_name] = "jplayer"
libraries[jplayer][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[modernizr][download][type] = "get"
libraries[modernizr][download][url] = "https://github.com/Modernizr/Modernizr/archive/master.zip"
libraries[modernizr][directory_name] = "modernizr"
libraries[modernizr][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[underscore][download][type] = "file"
libraries[underscore][download][url] = "http://underscorejs.org/underscore-min.js"
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type] = "library"


